### ISSUE TITLE
[Feature] Gallery like way to look at pictures.

### ISSUE THREAD

**Issue by Noneus** [haiwen/seadroid#12]
I store images in seafile. Looking at them in the webfrontend is fine. But in the android app when clicking a picture it downloads the whole thing. Some sort of thumbnail and small preview caching would be nice. With swiping to get to the next picture.

**Comment by joeplus** [comment]
Hey, I just stumbled upon seafile and I think it is a great solution!

Is there any news regarding the thumbnail implementation, I think there are changes required on the server side? Some comments above mentioned that it would be in release 1.8, is that correct?

**Comment by Logan676** [comment]
Seafile Android does support thumbnail preview if you have install the latest version.

Since the comment answered at `May 1, 2013`, things have changed quite differently. Now both Seafile server and Android client supports thumbnail already.

But the problem is android client doesn\`t download them from server, instead it calculates thumbnails locally. So we plan to add download thumbnails features soon.

**Comment by joeplus** [comment]
I saw that thumbnails are both used on server an client but they are used separately. But very nice to hear, that the download of thumbnails is on your roadmap, since this is the valuable part!

**Comment by akopper** [comment]
I also store a lot of images on Seafile and really love it.
Would be great to have left/right swipe support to view the next/last image. Also a thumbnail style view would be awesome.

**Comment by vascorppor** [comment]
That's right, photo swipe support would be great.
