### ISSUE TITLE
wish-list: add landscape view

### ISSUE THREAD

**Issue by kuyper** [haiwen/seadroid#217]
Great tool. I use it on my tablet as well, which I often operate in landscape mode in a keyboard stand. It would be great if seafile would not switch back to portrait mode in that case.

**Comment by Logan676** [comment]
Since you are fond of landscape view, are you using tablets? The reason we only support portrait perspective right now is because layout on tablets may get messed up.

We will optimize the ui for tablets in the future, includes layouts, fonts and colors. etc. (maybe need to create another copy of layout specifically).

Generally, user does\`t input rapidly, only when login, edit markdown docs and others. So it\`s not an emergency according to our agenda. You can do it yourself just by remove the configuration line in AndroidManifest. Hope it hopes.
