### ISSUE TITLE
Thumbnail to small & Star file Thumbnail ?

### ISSUE THREAD

**Issue by mickeyboss123** [haiwen/seadroid#241]
Version 1.4.1 Download on google
![18407](https://cloud.githubusercontent.com/assets/1274528/5720491/edc2e1be-9b5f-11e4-81b9-9b6e86f05375.jpg)
![18406](https://cloud.githubusercontent.com/assets/1274528/5720490/edc2e484-9b5f-11e4-9ad7-2148b7512d58.jpg)

**Comment by Logan676** [comment]
Thanks, I can reproduce this error, this was caused by thumbnail size [calculation algorithm](https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/data/DataManager.java#L187) which depends on display density dpi. Instead of calculating locally, we will change to download thumbnails from server side.

**Comment by mickeyboss123** [comment]
Thanks for your reply.
