### ISSUE TITLE
Seafile 1.4.1 not working on Galaxy Note 10.1

### ISSUE THREAD

**Issue by LeonFourie** [haiwen/seadroid#244]
Seafile 1.4.1 installed on Galaxy Note 10.1 with Android 4.1.2. Can't get it to run. It opens the screen that ask to add an account. If I press on the button the program stops working with a message "Unfortunately, Seafile has stopped". The same happens on another Galaxy Note with the same Android version.

**Comment by Logan676** [comment]
I can\`t reproduce the error, it will be helpful for us to fix the error if you append the cash log.

**Comment by LeonFourie** [comment]
Where do I find the log file?  It is not under the Seafile folder, even with hidden files showing.

**Comment by Logan676** [comment]
In android world, you need to connect your tablets to the PC via usb cable in order to get the log printed.

There are several tools to get the log, but all of them require [Android Dev environment](https://github.com/libgdx/libgdx/wiki/Setting-up-your-Development-Environment-(Eclipse,-Intellij-IDEA,-NetBeans)).
1. [Android Logcat](https://www.youtube.com/watch?v=2AHJsRKa_J8) -- a plugin which both available in Android Studio, Intellij and Eclipse IDE. 
2. use [command line](http://developer.android.com/tools/help/logcat.html) `adb logcat *:E` via a terminal.

**Comment by LeonFourie** [comment]
Is version 1.0 or 1.1 of Seafile not stil available because it stopped
working with one of the latest upgrades. It is my work tablet so I don't
have full rights to install and change things.

**Comment by Logan676** [comment]
can you successfully login your account on other platforms, like the Seafile website, Seafile desktop client or Seafile iOS client?

**Comment by LeonFourie** [comment]
Yes, desktop and website works perfectly . Synchronisation is also running
between PC and website.

**Comment by Logan676** [comment]
Does it work if you upgrade Seafile to 1.7.0 (the latest version)?
