### ISSUE TITLE
Camera photos not uploading, queue empty.

### ISSUE THREAD

**Issue by radry** [haiwen/seadroid#269]
On my Phone (Ascend P6; Android 4.4.2) Seafile doesn't upload camera files although I'm connected to wifi and also enabled allow 3G. When I create a new library and set it for camera files ONE random photos is uploaded and after that nothing more. The wifi is fast enough and I left the Seafile client open to ensure it is not closed by the system. 
The upload queue is EMPTY and doesn't show any files although there are many photos on the phone. There seems to be no way of forcing a sync of camera photos. 

I tried opening the photos in the Galery app and also snapping a new one. Nothing works. Seafile doesn't recognize or upload it.

**Comment by lins05** [comment]
This is quite weird. @Logan676 do you have a clue how this could happen?

**Comment by Logan676** [comment]
AFAIK, Ascend P6 has two kinds of storages, 8G internal storage and a microSD card. If the photos you want to upload saved on the microSD card, instead of the internal storage, there will be ignored. 
The camera upload service isn\`t that smart to scan on the secondary storage right now, we plan to add a new feature to support user choosing some specific directories soon. 
FYI, [let user choose which photo directories they want to upload](https://github.com/haiwen/seadroid/issues/151)

**Comment by radry** [comment]
@Logan676
Thanks for your advise. I checked the folder structure of the Ascend P6 and it is as follows:

/
|-storage
   |--sdcard 0 (symlink to /emulated/0)
   |--sdcard 1
   |--emulated
       |---0
|-sdcard (symlink to /storage/emulated/0)

So as you can see the device emulates an sdcard in the internal memory. When setting the official camera app to "internal" memory it save images to /storage/emulated/0/DCIM.
Only pictures in THIS FOLDER get uploaded. However this is a serious flaw as it neither uploads photos from 3rd party apps (such as camerazoom fx which saves to it's own folder on default) nor pictures from the real sdcard!! 

So everyone who uses a different camera app than the official one (not just on my phone but every) can't use the camera photo functionality.
