### ISSUE TITLE
Never uploads photos not taken directly through camera app e.g. twitter

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seadroid#342]
If I take photos via the camera app, all is good.

However, if I take photos via an app, like a Twitter client, even though those image files go into the same folder, they are never sync'd.

Is Seadroid listening for particular events, rather than just scanning the folders now and again in case it missed anything ?

**Comment by Logan676** [comment]
> Is Seadroid listening for particular events, rather than just scanning the folders now and again in case it missed anything ?

No, Seadroid is not only listening for camera events but also scanning folders (if camera upload service was turned on). But there are some restrictions of the upload folders, if you have seafile-1.6.0+ installed, only files under auto scanned or custom selected folders could be uploaded, others will be ignored.

Another reason is, we have only tested the built-in camera event, so events triggered by the third party app like Twitter client may not be handled. Welcome PRs to implement this feature because we didn\`t use twitter. As a workaround you can turn on the camera upload service and choose the folder for uploading. Though it may ignore the capture event when you take pics by Twitter client, it can upload it later.

**Comment by tomchiverton** [comment]
@Logan676 why did you close this ? This *is* the requested PR to implement auto upload of 3rd party taken photos ?

**Comment by Logan676** [comment]
Will add support of this in the future
