### ISSUE TITLE
Picture upload not acting as service? 

### ISSUE THREAD

**Issue by resuser** [haiwen/seadroid#375]
When I first tested the picture upload feature, it worked great. I would take a picture, and within a few seconds it would be in my library.

However, several times now I have opened up seafile on my phone and found that it hasn't been uploading for several days. As soon as I open the library, it starts uploading all the pictures it forgot to upload before. 

It appears to me that the service watching for new pictures stops running after a while.

**Comment by resuser** [comment]
Running seafile 1.7.1 on android 4.4.4

**Comment by Logan676** [comment]
Camera upload feature was indeed implemented by a background service, if it appears to stop running for a while, it may caused by the OS side, which has killed the service. have you used a (third party) memory optimization & acceleration tool or cleaned up the cache?

FYI, we have introduced a notification in order to keep camera upload service at the foreground when uploading new photos, can you find the notification bar (with a Seafile logo) in the notification area when uploading the pictures. If the notification disappeared, means that the background service has been killed.

**Comment by resuser** [comment]
I don't use any memory freeing programs. Android does this pretty well on its own. 
I'm used to the functionality of the Dropbox upload feature. I can forget about it for months and it still uploads. I'd be willing to run seafile with a notification as a fix until a proper service is implemented. Has this feature been pushed to f-droid yet? I don't see it in my version.

**Comment by Logan676** [comment]
Yes, actually we have release this feature since [Seafile-1.6.3](https://github.com/haiwen/seadroid/releases/tag/1.6.3).
If you are using Seafile-1.7.1 from Google Play Store, it should support this as well.

**Comment by resuser** [comment]
I've never seen Seafile put any .  Is this an option in the settings somewhere?  I haven't been able to find it.

I see the camera upload and file monitor services.  I will have to check in a few days to see if they're still running without opening the seafile app again.

**Comment by resuser** [comment]
I think I may have found the problem.  I just rebooted my phone and looked at the running processes.  It appears that seafile does not automatically register its services on boot.

**Comment by Logan676** [comment]
> I've never seen Seafile put any icons in the notification area. Is this an option in the settings somewhere? I haven't been able to find it.

No, there isn\`t any options in settings. Sorry for the mistake I have made, actually we haven\`t publicly released  such a version, that\`s why you couldn\`t find it. see #265 

> I see the camera upload and file monitor services. I will have to check in a few days to see if they're still running without opening the seafile app again.

I am afraid that they won\`t running if you left the app at the background for a few days, because we just made the camera upload service as a normal **background** service. 

> It appears that seafile does not automatically register its services on boot.

Yes, it won\`t start automatically on boot.
