### ISSUE TITLE
Implement Material Design

### ISSUE THREAD

**Issue by matpat996** [haiwen/seadroid#399]
What about Material Design? Are you going to implement it? Since I'm also an anroid developer, i could try to migrate seafile to MD.

**Comment by Logan676** [comment]
@matpat996 Yes, we are more than wanted to migrate Seafile to material design. 

Actually there are plenty of feature requests out there so the team have to focus on implementing the functional features. :smiley: But we are more than welcome that developers from the open source community can help us with those fancy features, e.g. material design, [Android Studio](https://github.com/haiwen/seadroid/pull/185) etc.
BTW, please create the pull request based on `develop` branch before you submit it. 
I will review the patch carefully and add your author info and [license](https://github.com/haiwen/seadroid/blob/master/THIRD_PARTY_LICENSE.md) after the patch was merged.

Regards,
Logan Guo

**Comment by matpat996** [comment]
@Logan676 I'll take a look at the existing code and then I'll try to implement it. 
BTW, where can I find the code conventions of seadroid (e.g. space after if and left parenthesis)?

**Comment by Logan676** [comment]
It\`s not a must to strictly follow Seadroid code convention for contributors, because I will review the patch and reformat the code when necessary. Actually we follow the [Code Conventions for the Java Programming Language](http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html) from the official docs. 
The links below are some important conventions from the document.
* [White Space](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141388.html)
* [Naming Conventions](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html)
* [Programming Practices](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-137265.html)
* [Code Examples](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-137946.html)
