### ISSUE TITLE
F-Droid version does not build

### ISSUE THREAD

**Issue by silberzwiebel** [haiwen/seadroid#428]
Hi there,

I know, you do not support the F-Droid release of your app, but maybe you are able to fix the build error which is logged here: https://f-droid.org/wiki/page/com.seafile.seadroid2/lastbuild_39

Would be really nice to be able to use seadroid via F-Droid.

Thank you,
silberzwiebel

**Comment by Logan676** [comment]
From the error log, I can tell that it caused by the newly introduced library [PagerSlidingTabStrip](https://github.com/astuetz/PagerSlidingTabStrip).

I will try to modify the xml file, e.g [tabs_main](https://github.com/haiwen/seadroid/blob/master/res/layout/tabs_main.xml#L19) to change the `xmlns:PagerSlidingTabStrip="http://schemas.android.com/apk/res-auto"` to be `xmlns:PagerSlidingTabStrip="http://schemas.android.com/apk/lib/com.seafile.seadroid2"` and create a new tag in order to trigger a fresh F-Droid build. 

Also I already reported the problem onto F-Droid [issue tracker](https://gitlab.com/fdroid/fdroiddata/issues/37)

see the same [questions](http://stackoverflow.com/a/14299159/3962551) from StackOverFlow

**Comment by Logan676** [comment]
> From the error log, I can tell that it caused by the newly introduced library PagerSlidingTabStrip.
> 
> I will try to modify the xml file, e.g tabs_main to change the xmlns:PagerSlidingTabStrip="http://schemas.android.com/apk/res-auto" to be xmlns:PagerSlidingTabStrip="http://schemas.android.com/apk/lib/com.seafile.seadroid2" and create a new tag in order to trigger a fresh F-Droid build.

It turned out that the fix above didn\`t solve the build error. 
The reason is (quoted from F-Droid [issue tracker](https://gitlab.com/fdroid/fdroiddata/issues/37))
>The easiest way to keep builds on F-Droid working and updates being fast is to switch to Gradle. Pull your dependencies from mavenCentral or jcenter, they should all be there.
Then, we can just build your app with gradle assembleRelease. Right now, it's hard for you to reproduce our build and it's not possible for us to use your maven setup, since it relies on binaries on a github repo as a maven repository.

Maybe it is time to migrate Seadroid from maven to gradle.

**Comment by freeplant** [comment]
@silberzwiebel  Do you know what we need to do to get F-Droid version updated?

**Comment by saljut7** [comment]
@silberzwiebel 
Hi, there are several request in Seafile forum for the outdated F-Droid apk for Seafile. As far as I understood this is because of the build problem discussed here (and you are the maintainer of the F-Droid apk)?
I would offer support and help for maintaining (I'm F-Droid only user and are quite dependent of up-to-date releases).

Thanks alot for offering Seafile on F-Droid!
sj7

**Comment by Logan676** [comment]
done, see the latest version from https://f-droid.org/repository/browse/?fdfilter=seafile&fdid=com.seafile.seadroid2
