### ISSUE TITLE
"Share item" not working?

### ISSUE THREAD

**Issue by HW71** [haiwen/seadroid#450]
Hi all,

I just configured a Seafile server on my Raspberry and tried to verify if it's possible to use the "Share" option in Android to upload content to my Seafile server.

Actually "Seafile" shows up in the list of Apps to use to share the content - but if I tap on the Seafile entry I just get a white page and nothing happens.

I'm wondering, if this is a feature still to be implemented - or if there's a usage error?

Steps to reproduce:
(1) Install Seafile on smartphone + configure App correctly
(2) open any web page in Google Chrome
(3) open Chrome menu by tapping three dots in upper-right corner
(4) tap "Share"
(5) in the list of available Apps to share: locate and tap "Seafile" entry 

Expected result:
Seafile app opens and offers possibility to save current link - maybe with title of web page as title of note in Seafile server.

Actual result:
Just a white page shows-up with "Seafile" in upper-left corner... :-(

Thanks so much in advance for any hints!

Have a great one & Cheers!

**Comment by Logan676** [comment]
Seafile App was designed to handle files rather than links, it doesn\`t make sense to save a link without attaching a specific file. You can simply use the **Add bookmark** which is chrome`s built-in feature.

**Comment by RoestVrijStaal** [comment]
Why not making a page with back button that sharing links isn't possible? Or better, not making SeaDroid an "Share via"-handler anymore, since uploading via the app seems the safest way. Granted, it's radical, but the best solution. 

At a chat-app I was stuck at SeaDroid's whitescreen every time when I pressed "Share via". It was impossible to pick a different handler. It could be only fixed by uninstalling SeaDroid. Which costs me time to reinstall and setup it again :-1:  :rage: :anger:
