### ISSUE TITLE
Duplicate photo upload

### ISSUE THREAD

**Issue by schwabe** [haiwen/seadroid#503]
When I disable/enabled/change the mobile photo sync Seafile starts to reupload some of the files.

The files that are affected are files that already exist and have a different size:

e.g.:

Device:
DSC_0001.jpg (content A)

Seafile:
DSC_0001.jpg (content B)
DSC_0001 (1).jpg (content A)

The app will not notice that the file already exists and create a third file on the server, leading to:

Seafile:
DSC_0001.jpg (content B)
DSC_0001 (1).jpg (content A)
DSC_0001 (2).jpg (content A)

**Comment by forouher** [comment]
Yes, that seems about right. The issue is only the latter file, "DSC_0001 (2).jpg". It's a duplicate upload. Seadroid indeed only makes the compare with the original file "DSC_0001.jpg", not with any later uploads.

I guess Seadroid might as well scan all the "* (?).jpg" files and see if the file in question has already been uploaded.

But, in any case, this duplicate upload should only happen once - whenever you modify the camera upload settings.

**Comment by schwabe** [comment]
@forouher Yes. Scanning all the "* (?).jpg" is probably the right solution. My problem is that just added the Screenshots to the list of uploaded folders and got 200 duplicates files because my new phone started from DSC_0001 again :(.

**Comment by jult** [comment]
Isn't there a way you could fuse with syncthing ? They've done it all before already, it works great, [especially on their android app](https://github.com/syncthing/syncthing-android), but they don't offer a decent user-based UI like seafile has, AND most importantly, they only offer a one user system install (which is really weird). You should join forces and make seafile the best there is.

**Comment by Logan676** [comment]
> My problem is that just added the Screenshots to the list of uploaded folders and got 200 duplicates files because my new phone started from DSC_0001 again

Sorry but Seafile Android client doesn\`t support to distinct them yet, It would work properly in your case if the API2 offered a way to query the hash of a file. But now comparing the file size is the best we can do.
