### ISSUE TITLE
Downloading of files above 2GB fails

### ISSUE THREAD

**Issue by bitcointools** [haiwen/seadroid#570]
When trying to download a file of 2.1 GB (size as showed in the app) to my local device, it shows up as 1.2MB file on the download list. It progresses through 2.1 GB / 1.2 MB. The phone's notification window shows bizarre percentage numbers and download never completes. File does not show up in phone's folder. Smaller files can be downloaded successfully.

**Comment by Logan676** [comment]
Thanks for your report, in order to locate the bug,
1. Which version are you using?
2. Did you download the large file under an encrypted library? If yes, have you turned the client-side-encryption setting on?

**Comment by bitcointools** [comment]
1) 2.1.3 
2) I am not using an encrypted library

**Comment by Logan676** [comment]
Aha, I have reproduced the bug. In my case, I have downloaded a 2.6GB large file, seems like that it is easier to reproduce the bug by downloading a small file first and then download the large one.

> The phone's notification window shows bizarre percentage numbers and download never completes.

From my observing, what the difference with yours, is I have successfully downloaded the large file for a really long period of time.

The bizarre percentage numbers appears both in notification window and transfer list is due to the total size was not updated correctly. see the PR #582 for more details.
