### ISSUE TITLE
No permission requests for GET_ACCOUNTS on Android 6

### ISSUE THREAD

**Issue by denis-bogdanas** [haiwen/seadroid#613]
Hello, I'm Denis Bogdanas, a research assistant at Oregon Stat University.
I'm working on a tool that automatically introduces runtime permission checks and requests for Android 6 apps. As part of this study I analyzed this app, looking for how permissions are referred in the code.

This app uses permission GET_ACCOUNTS but there are no runtime permission checks for it. As a result, protected methods
relying on this permission will return empty or incomplete results on Android 6.

Here are code locations indentified by our tools that use GET_ACCOUNTS:

```
<android.accounts.AccountManager: android.accounts.Account[] getAccountsByType(java.lang.String)>
	from <com.seafile.seadroid2.account.AccountManager: java.util.List getAccountList()> L: 49
	from <com.seafile.seadroid2.account.AccountManager: java.util.List getSignedInAccountList()> L: 59

<android.accounts.AccountManager: android.accounts.Account[] getAccounts()>
	from <com.seafile.seadroid2.ui.EmailAutoCompleteTextView: java.util.Set getEmailAccounts()> L: 65

<android.accounts.AccountManager: void addOnAccountsUpdatedListener(android.accounts.OnAccountsUpdateListener,android.os.Handler,boolean)>
	from <com.seafile.seadroid2.ui.activity.AccountsActivity: void onCreate(android.os.Bundle)> L: 126
	from <com.seafile.seadroid2.provider.SeafileProvider: boolean onCreate()> L: 136
```

Do you think this is a bug?

best regards,
Denis

**Comment by forouher** [comment]
Hi Denis,

thank you very much for doing these checks! 

I doubt this is a bug. Android 6 corresponds to API level 23. Since API level 23, one does not actually need the GET_ACCOUNTS permission anymore to call the framework methods to mentioned.

Please have a look at the API doc of AccountManager for details:
https://developer.android.com/reference/android/accounts/AccountManager.html#getAccountsByType(java.lang.String)

In fact, Seadroid does not take the GET_ACCOUNTS anymore starting with API level 23, as can be seen in its manifest:
https://github.com/haiwen/seadroid/blob/master/app/src/main/AndroidManifest.xml#L23

cheers
Dariush

**Comment by denis-bogdanas** [comment]
Thanks for answer! Your answer helped me understanding various permission configs better.
