### ISSUE TITLE
Android: Cannot enable seafile account sync

### ISSUE THREAD

**Issue by maybeec** [haiwen/seadroid#625]
Hi there, for some time now I experience the problem, that I cannot upload any data to my private seafile server using the seafile android app.
Finally, I found some reports in the seafile forums regarding the seafile account to be disabled on android device. It turned out, that this happens to me as well. So under settings -> accounts -> seafile I found "synchronization disabled", but "synchronize now" even does not enable it. I also checked the global "automatic sync" setting of my device, which is enabled. So no worries about that.
I even tried to remove the seafile account entirely and recreated it. No improvements...

Just for information: I did not enable automatic foto upload. I just want to upload selected pictures on demand.

Any idea how to get seafile app synchronized again?
Android 6.0.1 - Moto X Play

**Comment by forouher** [comment]
Account sync on Android ist just for camera sync. Manually uploading files via the Android app is independent from the account sync settings and should work regardless.

I suggest to try uploading a file from a PC via the seafile web interface. If that doesn't work either,  it would strongly suggest that your problem lies with the server configuration. 

Am 12. Februar 2017 13:26:32 MEZ schrieb Malte Brunnlieb <notifications@github.com>:

**Comment by maybeec** [comment]
Thanks! Bad configuration was the problem.
Good to know, that web upload and app upload are working with the same stack.
