### ISSUE TITLE
Missing folder when other app uses "share via seafile"

### ISSUE THREAD

**Issue by jedreg** [haiwen/seadroid#648]
Hi
I have a library that few subfolders down has sibling folders let say A,B,C,D. When I open seafile app regularily I can see all these subfolders. If I start from other app and try to save PDF using "share via" option then navigating down to the same place shows all but recently created D folder (that was added an hour ago). What is surprising when I create one more directory called E, then I can see again all A,B,C,D but E !! Quite frustrating as I want to push recent files to recently created folder :/ Is that a "known feature"? I am on 6.0.2 server on ubuntu, seafile app 2.1.11.

**Comment by xiroaf** [comment]
Hi

I think this is a global display issue in the "selection windows". It looks like that action buttons ('OK' or 'Cancel' or whatever on the bottom of the window) cover the last list entry. It can be experienced in numerous cases.
For example: When you want to copy or move a file and in the target selection window have more elements to display than can be fit in the selection list, the last entry (what is the last modified) covered by the bottom button and you can't select this entry because it is not visible behind the button.

Environment:
Seafile server (docker container) version: 6.1.1
Android Client: 2.1.16 (running on Android 6.0)

**Comment by jkronen** [comment]
I experience the same issue with App version 2.1.6 and 2.1.16.
Server is 6.1.1

**Comment by dreua** [comment]
Still there in App version 2.2.8. In portrait mode I can see all my libraries (because there is enough space) while in landscape mode the last is not visible even when scrolling all the way down.

**Comment by golf1** [comment]
I'd like to confirm the observation of @dreua . Also in portrait mode the last entry on the bottom is hidden by the "Cancel" or by the "Cancel"/"OK" buttons.
A work around is to create another entry to move the list one up.

**Comment by Gustl22** [comment]
Weird...I wanted to fix this, but issue doesn't appear in current master...

Which branch is used for the releases? Or better: why there's a difference?

<img src=https://user-images.githubusercontent.com/18537755/51410471-0588a980-1b65-11e9-9b16-2b4baac12ac6.jpg width="310" align="left">
<img src=https://user-images.githubusercontent.com/18537755/51410893-33bab900-1b66-11e9-8c91-08d8c4aa5c80.jpg width="310" align="left">

**Comment by Gustl22** [comment]
Issue seems to be eradicated in 2.2.12, so can close this issue. @jedreg can you confirm?

**Comment by jedreg** [comment]
Indeed it is no more an issue for some long time. I am on 2.2.14 on Samsung
S9 / Android 8.0 and in this setup it works as expected.
-andy.
