### ISSUE TITLE
Cannot open encrypted libraries with 2.2.3

### ISSUE THREAD

**Issue by dbet1** [haiwen/seadroid#745]
Since version 2.2.3 I cannot open an encrypted library.
After I give in the password for the library I receive the message FORBIDDEN. If I give a wrong password there is the message "password incorrect". But I give the right password there is always the message FORBIDDEN.

**Comment by freeplant** [comment]
Can't reproduce the problem.

**Comment by dbet1** [comment]
I have tested version 2.2.1 and 2.2.4 with two devices which have two different Android versions. The test scenario was to open an encrypted library, then open a file, change something in this file and save the file. Afther that I checked that it is uploaded to the library. The same I tested with unencrypted libraries.

*** Version 2.2.1 ***

Samsung Galaxy Note 8.0 mit Android 4.4.4
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Download of documents, the change and upload are OK. It works with encrypted and unencrypted libraries.

Samsung Galaxy Tab S3 mit Android 8.0.0
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Documents were downloaded as new file, I have to save it local, then uploade to seafile. This is unusable.


*** Version 2.2.4 ***

Samsung Galaxy Note 8.0 mit Android 4.4.4
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Documents are downloaded, but after a change they cannot be upload. The error message is not helpful: Upload failed.
- During a second try there was an app abort during download. After that, I can't download any file in an encrypted library. I had to change to "encrypt data on the server", after that I could download the file again, but upload also failes.
- Documents in unencrypted libraries can be downloaded but also not uploaded: Upload failed.

Samsung Galaxy Tab S3 mit Andorid 8.0.0
- Passwords for encrypted libraries were not accepted at all! If I type the password correct, I receive the error FORBIDDEN, if I made a typo in the password, I receive "Wrong password", which is correct.
- Documents were downloaded as new file, I have to save it local, then uploade to seafile. Tested only with unencrypted libraries because of the error with passwords.

*** Conclusion ***
Because the Note 8.0 I don't use anymore I have still to stay with version 2.1.13. With this version the Dowload/Upload is correctly also on the Tab S3. But passwords of encrypted libraries are forgotten if I use "encrypt data local". If I use "encrypt data on server" they are forgotten after an hour or so. This is normal and by design, but if I use "encrypt data local" passwords should be saved as in the desktop version or the one for iOS.

Seafile is a wonderful piece of software, but the android app is a pain.

**Comment by freeplant** [comment]
What server version do you use?

**Comment by dbet1** [comment]
6.2.5

**Comment by macearl** [comment]
I have the same problem, also running Server 6.2.5, i now downgraded my Seafile Android Client to 2.2.2 and everything is working again.

**Comment by dbet1** [comment]
Which Android version do you have?
Using seadorid 2.2.2 do you lost passwords after app close?
Can you download a document, change it and it would be uploaded correctly?

**Comment by macearl** [comment]
Android: 7.1.2 (LineageOS 14.1)
Seadroid: 2.2.2

Password for encrypted libraries is forgotten after i close the app (this was always the case for me, it never rememdered it)
If i download a text file, change it, hit upload manually inside the app (the change is not detected automatically), it says upload finished, however it is still the old unchanged version of the file (i think this is also the case for me for quite a while now, i dont really change files on my phone and reupload them, i mostly just download stuff, and redownload once the file got changed on my Desktop or Notebook)

I now updated my Seafile Server to 6.3.2 and will test the newest seadroid version again.


on another note: since i purged all data from the app and reinstalled it i cant save my files to the internal storage anymore, it always gets placed in `externalstorage:android/media/com.seafile.seadroid2/$accountname ($serveradress)/$reponame/` which is also kind of annoying as the newer android versions do not let most apps edit files from external storage.

**Comment by aarnaud** [comment]
Same issue on encrypted libraries after typing the correct password for the library:  "FORBIDDEN" 
Android: 7.1.2 (LineageOS 14.1)
Seadroid: 2.2.4
seafile-server-6.2.5

**Comment by freeplant** [comment]
@aarnaud Can you try with server version 6.3.2? In the client, do you turn the option "local encryption" on or off?

**Comment by dbet1** [comment]
I also upgraded the server to 6.3.2. On Android 8 with seadroid 2.2.6 passwords are not lost any more. But on Android 4.4.4 with seadroid 2.2.6 the problem ist still there.

**Comment by freeplant** [comment]
Android 4.4.4 is a too old version. Maybe the API we used can't work on this version.
