### ISSUE TITLE
v2.2.12 has same versionname/versionCode as v2.2.11

### ISSUE THREAD

**Issue by IzzySoft** [haiwen/seadroid#785]
Looks like you forgot to increase `versionCode` and update `versionName` in your `app/build.gradle` when releasing v2.2.12 – which is why [F-Droid cannot update](https://gitlab.com/fdroid/fdroiddata/issues/1532). Could you please fix that and "move the tag" to point to the fixed version? Thanks!

**Comment by dreua** [comment]
This might be unrelated - I am not familiar with the internals of - but [Google play](https://play.google.com/store/apps/details?id=com.seafile.seadroid2&hl=de) also lists 2.2.11 as the latest version. (On the page as well as in my fully updated app. Which suffers from #776 which should be fixed by v2.2.12.)

**Comment by SaudM** [comment]
fixed it

**Comment by IzzySoft** [comment]
Thanks!
